# Generated by Django 4.0 on 2023-12-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('itmoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickle_model',
            name='pickle',
            field=models.FileField(upload_to='pickle/<function user_directory_path at 0x0000023700FE8940>'),
        ),
    ]
