# Generated by Django 4.0 on 2023-12-10 08:37

from django.db import migrations, models
import itmoApp.models


class Migration(migrations.Migration):
    dependencies = [
        ('itmoApp', '0002_alter_pickle_model_pickle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mse', models.CharField(max_length=100)),
                ('mspe', models.CharField(max_length=100)),
                ('mape', models.CharField(max_length=100)),
                ('rmse', models.CharField(max_length=100)),
                ('mae', models.CharField(max_length=100)),
                ('r2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pickle_model',
            name='pickle',
            field=models.FileField(upload_to=itmoApp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='pickle_model',
            name='metrics',
            field=models.ManyToManyField(to='itmoApp.Metric'),
        ),
    ]
